title: Sheffield FOI Explorer
description: Explore Freedom of Information requests in Sheffield.
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

repository: peterkarakostas/Sheffield_FOI_Webapp
show_downloads: false
